### PR TITLE
Release v0.2.0

### PR DESCRIPTION
**Pull request by nulltoken**
Fixes #[ISSUE_NUMBER].

**Checklist**

- [ ] Tests added / updated
- [x] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by philsturgeon** [comment]
The latest release is v0.1.0 not v0.0.1, the README is lying. It’s based off of tags and releases on GitHub. Can we make everything agree that it’s now v0.2.0? 

--
Phil Sturgeon
DevRel @ Stoplight.io

**Comment by nulltoken** [comment]
> The latest release is v0.1.0 not v0.0.1, the README is lying. It’s based off of tags and releases on GitHub. Can we make everything agree that it’s now v0.2.0?

@philsturgeon Fixed!

**Comment by philsturgeon** [comment]
Excellent! Leave the release aspect to me I’ll sort it out later. I have to see what is still automated and what needs to be done manually, and I’m working a US day today.

**Comment by tillig** [comment]
Nice work getting this out the door! I've published an update to my original extension that will pop up a webview instructing folks to switch over (and it provides a convenient link that brings up the extensions window with our two extensions displayed for easy switching). It's also clearly marked as deprecated in the README and package description, pointing folks to this official extension.

I'll leave the update there for, oh, a month to make sure folks auto-update and get the note, then I'll unpublish mine so this official one is the only one remaining listed in the marketplace.

**Comment by philsturgeon** [comment]
@tillig thank you so much, for the hard work you put into getting this done in the first place, to the continued cooperation you've shown in getting the PRs merged, and for helping remove any chance for confusion from existing users. This has been a rarely cordial experience and I'm very grateful for your help! :D 

Here's 500 trees and 5 tonnes of CO2 removed as a thank you! https://ecologi.com/philsturgeon?tree=5f15d4f1964e83001788cd6b

**Comment by tillig** [comment]
Thanks! I'm so happy this all worked out. And TREEEEES! 🌲 🌳

**Pull request merged**
